name: Spider

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Clone project
      run: |
        rm -rf project
        rm -rf jar/custom_spider.jar
        git clone --recurse-submodules https://github.com/FongMi/CatVodSpider project
      
    - name: Customize Spider
      working-directory: ./project
      run: |
         #添加Misc&crawler
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/utils/Misc.java > app/src/main/java/com/github/catvod/utils/Misc.java
         

       
        
         #添加AppYsV2
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/AppYsV2.java > app/src/main/java/com/github/catvod/spider/AppYsV2.java
         sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/AppYsV2.java
         

         #添加IQIYI&MGTV&DOUBAN
         
         #curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/IQIYI.java > app/src/main/java/com/github/catvod/spider/IQIYI.java
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/IQIYI.java
         #curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/MGTV.java > app/src/main/java/com/github/catvod/spider/MGTV.java
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/MGTV.java
         #curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/DoubanForTVBox.java > app/src/main/java/com/github/catvod/spider/DoubanForTVBox.java
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/DoubanForTVBox.java

         
         #添加Live2Vod
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/bean/Live.java > app/src/main/java/com/github/catvod/bean/Live.java
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/Live2Vod.java > app/src/main/java/com/github/catvod/spider/Live2Vod.java         
         sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/Live2Vod.java

         #添加XYQBiu.java
         #cp ../app/src/main/java/com/github/catvod/spider/XYQBiu.java app/src/main/java/com/github/catvod/spider/XYQBiu.java
         #cp ../app/src/main/java/com/github/catvod/net/OKCallBack.java app/src/main/java/com/github/catvod/net/OKCallBack.java
         #sed -i 's/com.github.catvod.net.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/XYQBiu.java

         
         #简体化阿里云盘
         sed -i 's/原畫/原画/g' app/src/main/java/com/github/catvod/spider/Ali.java
         sed -i 's/原畫/原画/g;s/阿里雲盤/阿里云盘/g' app/src/main/java/com/github/catvod/ali/API.java
         
         rm -rf app/src/main/java/com/github/catvod/spider/Ysj.java
         rm -rf app/src/main/java/com/github/catvod/spider/Dm84.java
         rm -rf app/src/main/java/com/github/catvod/spider/Doll.java
         rm -rf app/src/main/java/com/github/catvod/spider/Ying.java
         rm -rf app/src/main/java/com/github/catvod/spider/Miss.java
         rm -rf app/src/main/java/com/github/catvod/spider/Jable.java
         rm -rf app/src/main/java/com/github/catvod/spider/Supjav.java
         rm -rf app/src/main/java/com/github/catvod/spider/Hanime.java
         rm -rf app/src/main/java/com/github/catvod/spider/Eighteen.java

    - name: Build the app
      working-directory: ./project
      run: |        
         chmod +x gradlew
         ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
         
    - name: Customize Spider Jar
      working-directory: ./project
      run: |        
         rm -rf jar/custom_spider.jar
         rm -rf jar/spider.jar/original/META-INF
         curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar > jar/3rd/apktool_2.7.0.jar
         java -jar jar/3rd/baksmali-2.5.2.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes
         mkdir -p jar/spider.jar/smali/com/github/catvod/
         mv jar/Smali_classes/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/         
         java -jar jar/3rd/apktool_2.7.0.jar b jar/spider.jar -c
         mv jar/spider.jar/dist/dex.jar ../jar/custom_spider.jar
         md5=($(md5sum ../jar/custom_spider.jar))
         echo $md5 > ../jar/custom_spider.jar.md5
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Spider
        path: ./jar/custom_spider.jar

    - name: Update spider jar      
      uses: EndBug/add-and-commit@v9.1.3
      with:
        default_author: github_actions
        message: 'update spider jar'
        add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"        
